import type { Command } from "commander";

export interface CompletionNode {
  /** Command name, e.g. "employee". Root node uses the program name ("gusto"). */
  name: string;
  /** "" for the root, "/employee", "/employee/job" for nested commands. */
  path: string;
  /** Direct child command names. */
  subcommands: string[];
  /** Option flag tokens for this command (long and short), e.g. ["--json", "-v"]. */
  flags: string[];
  /** Positional argument choice values declared on this command. */
  argChoices: string[];
  children: CompletionNode[];
}

export interface FlagChoice {
  flag: string;
  choices: string[];
}

export interface CompletionModel {
  root: CompletionNode;
  /** Flags with static choices, unioned across the whole tree (global flags live at the root). */
  flagChoices: FlagChoice[];
}

export function describeTree(program: Command): CompletionModel {
  const flagChoices: FlagChoice[] = [];
  const seenFlagChoice = new Set<string>();

  function walk(cmd: Command, path: string): CompletionNode {
    const subcommands: string[] = [];
    const children: CompletionNode[] = [];
    for (const sub of cmd.commands) {
      const subName = sub.name();
      subcommands.push(subName);
      children.push(walk(sub, `${path}/${subName}`));
    }

    const flags: string[] = [];
    for (const opt of cmd.options) {
      if (opt.hidden) continue;
      if (opt.short) flags.push(opt.short);
      if (opt.long) flags.push(opt.long);
      if (opt.argChoices && opt.long && !seenFlagChoice.has(opt.long)) {
        seenFlagChoice.add(opt.long);
        flagChoices.push({ flag: opt.long, choices: [...opt.argChoices] });
      }
    }

    const argChoices: string[] = [];
    for (const arg of cmd.registeredArguments) {
      if (arg.argChoices) argChoices.push(...arg.argChoices);
    }

    return { name: cmd.name(), path, subcommands, flags, argChoices, children };
  }

  return { root: walk(program, ""), flagChoices };
}

function flatten(node: CompletionNode): CompletionNode[] {
  return [node, ...node.children.flatMap(flatten)];
}

/** Words a node can complete: its subcommands, its positional choices, then its flags. */
function candidatesFor(node: CompletionNode): string {
  return [...node.subcommands, ...node.argChoices, ...node.flags].join(" ");
}

export function generateBashCompletion(model: CompletionModel): string {
  const pathArms = flatten(model.root)
    .map((n) => `    "${n.path}") opts="${candidatesFor(n)}" ;;`)
    .join("\n");

  const choiceArms = model.flagChoices
    .map((c) => `    ${c.flag}) COMPREPLY=( $(compgen -W "${c.choices.join(" ")}" -- "$cur") ); return ;;`)
    .join("\n");

  return `# bash completion for gusto (generated by \`gusto completion bash\`)
# Compatible with bash 3.2 (macOS system bash). On macOS run \`brew install bash-completion@2\`.
_gusto() {
  local cur prev cmd_path i w opts
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  case "$prev" in
${choiceArms}
  esac

  cmd_path=""
  for (( i=1; i < COMP_CWORD; i++ )); do
    w="\${COMP_WORDS[i]}"
    case "$w" in -*) continue ;; esac
    cmd_path="\${cmd_path}/\${w}"
  done

  opts=""
  case "$cmd_path" in
${pathArms}
  esac

  COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}
complete -F _gusto gusto
`;
}
